algoritmo "L01G_propriedade_distributiva"
var
   A, B, C, D: inteiro
inicio
   escreva("A: ") leia(A)
   escreva("B: ") leia(B)
   escreva("C: ") leia(C)
   escreva("D: ") leia(D)
   escreval("A+B=", A+B, "  A*B=", A*B)
   escreval("A+C=", A+C, "  A*C=", A*C)
   escreval("A+D=", A+D, "  A*D=", A*D)
   escreval("B+C=", B+C, "  B*C=", B*C)
   escreval("B+D=", B+D, "  B*D=", B*D)
   escreval("C+D=", C+D, "  C*D=", C*D)
fimalgoritmo
